# Generated by Django 2.1 on 2018-08-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('album_tittle', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('song_tittle', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
