# Generated by Django 2.1 on 2018-08-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180825_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=''),
        ),
    ]
